### ISSUE TITLE
queue:1:1: error: stray '\177' in program

### ISSUE THREAD

**Issue by awissu** [Eyescale/Collage#137]
More info from logfile:
...
[  209s] /home/abuild/rpmbuild/BUILD/Collage-1.0.0/tests/queue:1:1: error: stray '\177' in program
[  209s]  ELFso.2% I‹$L‰зяPH‹H‰ЯяP0и\ляяH‹L$(ёяяяярБѓи…АuH‹CHЌ{яPHЃДи
...
https://pmbs.links2linux.de/build/home:awissu/openSUSE_13.1/x86_64/Collage/_log
Project:
https://pmbs.links2linux.de/package/show/home:awissu/Collage

**Comment by eile** [comment]
Can't reproduce.
