### ISSUE TITLE
boost version

### ISSUE THREAD

**Issue by leo07046219** [Eyescale/Collage#221]
I come to wake up the sleeping project.
which boost version if collage and its sub project fits best? 
I use boost_1_75_0 to compile, and get some error: can't find some boost symbles.

**Comment by eile** [comment]
It's been a good year I've compiled Collage, back then it was on the boost version which comes with Ubuntu 18.04.

**Comment by leo07046219** [comment]
@eile
my problem solved, cause of the compile environment's incomplete boost lib. 
additionally,some missing lib routines in Collage cmake file.
Not the version problem.
Thanks all the same!
